/**
 * Exercises the PDF generators for real.
 *
 * jsPDF runs in Node, so the documents can actually be built and inspected
 * rather than only code-reviewed. This is worth doing because the generators
 * walk deeply nested plan objects — `plan.generation.warnings`, `meal.items`,
 * `day.exercises[].caution` — and the usual failure is a `TypeError` on an
 * optional branch that never appeared during manual testing.
 *
 * `save()` is stubbed because it reaches for the DOM; everything up to and
 * including the byte output is genuine.
 *
 *   node tests/pdf.test.mjs
 */
import assert from 'node:assert/strict';

let passed = 0;
let failed = 0;

const check = async (name, fn) => {
  try {
    await fn();
    console.log(`  PASS  ${name}`);
    passed += 1;
  } catch (error) {
    console.log(`  FAIL  ${name}\n        ${error.message}`);
    failed += 1;
  }
};

/* --- capture the generated bytes instead of triggering a download ------- */

const { jsPDF } = await import('jspdf');
const saved = [];
const realSave = jsPDF.API.save;
jsPDF.API.save = function stubbedSave(filename) {
  saved.push({ filename, bytes: this.output('arraybuffer').byteLength, doc: this });
  return this;
};

const { exportWorkoutPlanPdf, exportDietPlanPdf, exportGroceryListPdf } = await import(
  '../src/lib/pdf.js'
);

/* --- fixtures matching the server's stored plan shapes ------------------ */

const workoutPlan = {
  version: 3,
  splitType: 'push_pull_legs',
  daysPerWeek: 3,
  goal: 'muscle_gain',
  createdAt: '2026-08-01T00:00:00.000Z',
  generation: { generatedBy: 'ai', warnings: [] },
  guidelines: { sets: 4, reps: '8-12', restSeconds: 90 },
  safetyNotes: ['Overhead pressing removed — shoulder impingement recorded.'],
  days: [
    {
      dayIndex: 1,
      name: 'Push',
      description: 'Chest, shoulders and triceps.',
      exercises: [
        {
          order: 1,
          slug: 'barbell_bench_press',
          name: 'Barbell Bench Press',
          sets: 4,
          reps: '8-12',
          restSeconds: 120,
        },
        {
          order: 2,
          slug: 'cable_fly',
          name: 'Cable Fly',
          sets: 3,
          reps: '12-15',
          restSeconds: 60,
          caution: 'Keep the elbows soft.',
        },
      ],
    },
    // A day the injury filter emptied — the recovery branch.
    { dayIndex: 2, name: 'Recovery', description: null, exercises: [] },
  ],
};

const dietPlan = {
  version: 2,
  createdAt: '2026-08-01T00:00:00.000Z',
  generation: { generatedBy: 'fallback', warnings: ['AI unavailable.'] },
  targets: { calories: 2400, protein: 170, carbs: 250, fats: 70 },
  dailyTotals: { calories: 2380, protein: 168, carbs: 246, fats: 71 },
  variance: { calories: -20, protein: -2, carbs: -4, fats: 1, caloriePercent: -0.8 },
  meals: [
    {
      order: 1,
      name: 'Breakfast',
      totals: { calories: 620, protein: 42, carbs: 70, fats: 16 },
      items: [
        {
          slug: 'oats-rolled',
          name: 'Rolled Oats',
          grams: 80,
          unit: 'g',
          calories: 303,
          protein: 11,
          carbs: 54,
          fats: 5,
        },
        {
          slug: 'whey-protein',
          name: 'Whey Protein',
          grams: 30,
          unit: 'g',
          calories: 120,
          protein: 24,
          carbs: 3,
          fats: 2,
        },
      ],
    },
  ],
};

const groceryList = {
  days: 7,
  generatedFrom: { planVersion: 2, targetCalories: 2400, dailyCalories: 2380 },
  groups: [
    {
      aisle: 'Grains & staples',
      items: [
        {
          slug: 'oats-rolled',
          name: 'Rolled Oats',
          category: 'grain',
          aisle: 'Grains & staples',
          perDay: { amount: 80, unit: 'g' },
          purchase: { amount: 600, unit: 'g' },
          caloriesTotal: 2121,
          usedIn: ['Breakfast'],
        },
      ],
    },
  ],
  summary: {
    distinctItems: 1,
    aisles: 1,
    totalCalories: 2121,
    caloriesPerDay: 303,
  },
};

/* --- the documents build and contain real content ---------------------- */

await check('workout: builds a non-trivial PDF', async () => {
  saved.length = 0;
  await exportWorkoutPlanPdf(workoutPlan, { userName: 'Krunal Patel' });
  assert.equal(saved.length, 1);
  assert.ok(saved[0].bytes > 2000, `only ${saved[0].bytes} bytes`);
});

await check('workout: filename carries the user and the plan version', () => {
  assert.equal(saved[0].filename, 'fitgen-workout-krunal-patel-v3.pdf');
});

await check('workout: an emptied training day does not throw', async () => {
  // Already covered by the fixture's day 2, but assert the branch explicitly.
  const recoveryOnly = {
    ...workoutPlan,
    days: [{ dayIndex: 1, name: 'Recovery', exercises: [] }],
  };
  await exportWorkoutPlanPdf(recoveryOnly, { userName: 'x' });
});

await check('diet: builds a non-trivial PDF', async () => {
  saved.length = 0;
  await exportDietPlanPdf(dietPlan, { userName: 'Krunal Patel' });
  assert.equal(saved.length, 1);
  assert.ok(saved[0].bytes > 2000, `only ${saved[0].bytes} bytes`);
  assert.equal(saved[0].filename, 'fitgen-diet-krunal-patel-v2.pdf');
});

await check('grocery: builds a non-trivial PDF named for the day count', async () => {
  saved.length = 0;
  await exportGroceryListPdf(groceryList, { userName: 'Krunal Patel' });
  assert.equal(saved.length, 1);
  assert.ok(saved[0].bytes > 1000, `only ${saved[0].bytes} bytes`);
  assert.equal(saved[0].filename, 'fitgen-groceries-krunal-patel-7d.pdf');
});

/*
 * `variance` and `targets` have no Mongoose default, so a stored plan can lack
 * either. The document must still build — the meal tables are the part the user
 * actually needs — with the missing row dropped rather than the export failing.
 */
await check('diet: a plan with no variance still exports', async () => {
  saved.length = 0;
  const { variance, ...withoutVariance } = dietPlan;
  assert.ok(variance, 'fixture must have variance to remove');
  await exportDietPlanPdf(withoutVariance, { userName: 'a' });
  assert.equal(saved.length, 1);
  assert.ok(saved[0].bytes > 2000);
});

await check('diet: a plan with no targets or totals still exports', async () => {
  saved.length = 0;
  await exportDietPlanPdf(
    { version: 1, meals: dietPlan.meals },
    { userName: 'a' },
  );
  assert.equal(saved.length, 1);
});

await check('diet: a meal with no totals falls back to its name alone', async () => {
  saved.length = 0;
  await exportDietPlanPdf(
    {
      version: 1,
      meals: [{ order: 1, name: 'Snack', items: dietPlan.meals[0].items }],
    },
    { userName: 'a' },
  );
  assert.equal(saved.length, 1);
});

await check('diet: a long plan paginates', async () => {
  saved.length = 0;
  await exportDietPlanPdf(
    {
      ...dietPlan,
      meals: Array.from({ length: 8 }, (_, m) => ({
        order: m + 1,
        name: `Meal ${m + 1}`,
        totals: { calories: 500, protein: 30, carbs: 50, fats: 15 },
        items: Array.from({ length: 8 }, (_, i) => ({
          slug: `food-${m}-${i}`,
          name: `Food Item ${m + 1}-${i + 1} With A Long Name`,
          grams: 100,
          unit: 'g',
          calories: 120,
          protein: 8,
          carbs: 14,
          fats: 3,
        })),
      })),
    },
    { userName: 'a' },
  );
  const pages = saved[0].doc.getNumberOfPages();
  assert.ok(pages > 1, `expected multiple pages, got ${pages}`);
});

/* --- the parts most likely to break ------------------------------------- */

await check('a missing name still yields a usable filename', async () => {
  saved.length = 0;
  await exportWorkoutPlanPdf(workoutPlan, {});
  assert.equal(saved[0].filename, 'fitgen-workout-user-v3.pdf');
});

await check('a name of only punctuation does not produce a bare-dash filename', async () => {
  saved.length = 0;
  await exportWorkoutPlanPdf(workoutPlan, { userName: '!!!' });
  assert.equal(saved[0].filename, 'fitgen-workout-user-v3.pdf');
});

await check('absent optional sections are skipped rather than throwing', async () => {
  saved.length = 0;
  await exportWorkoutPlanPdf(
    {
      version: 1,
      splitType: 'full_body',
      daysPerWeek: 3,
      goal: 'fat_loss',
      days: [{ dayIndex: 1, name: 'Full body', exercises: [] }],
      // no createdAt, generation, guidelines or safetyNotes
    },
    { userName: 'a' },
  );
  assert.equal(saved.length, 1);
});

/*
 * Page breaks are the part a code review is least able to confirm: jsPDF has no
 * flow layout, so text that overruns is written off the bottom of the page
 * silently rather than erroring. A plan long enough to need several pages must
 * actually produce several pages.
 */
await check('a long plan paginates instead of overrunning one page', async () => {
  saved.length = 0;
  const longPlan = {
    ...workoutPlan,
    days: Array.from({ length: 12 }, (_, dayIndex) => ({
      dayIndex: dayIndex + 1,
      name: `Session ${dayIndex + 1}`,
      description: 'A deliberately long day used to force pagination.',
      exercises: Array.from({ length: 10 }, (_, i) => ({
        order: i + 1,
        slug: `exercise_${i}`,
        name: `Exercise Number ${i + 1} With A Long Name`,
        sets: 4,
        reps: '8-12',
        restSeconds: 90,
      })),
    })),
  };
  await exportWorkoutPlanPdf(longPlan, { userName: 'a' });
  const pages = saved[0].doc.getNumberOfPages();
  assert.ok(pages > 1, `expected multiple pages, got ${pages}`);
});

await check('a long grocery list paginates', async () => {
  saved.length = 0;
  await exportGroceryListPdf(
    {
      ...groceryList,
      groups: Array.from({ length: 8 }, (_, g) => ({
        aisle: `Aisle ${g + 1}`,
        items: Array.from({ length: 14 }, (_, i) => ({
          slug: `item-${g}-${i}`,
          name: `Grocery Item ${g + 1}-${i + 1}`,
          category: 'grain',
          aisle: `Aisle ${g + 1}`,
          perDay: { amount: 50, unit: 'g' },
          purchase: { amount: 400, unit: 'g' },
          caloriesTotal: 500,
          usedIn: ['Breakfast'],
        })),
      })),
    },
    { userName: 'a' },
  );
  const pages = saved[0].doc.getNumberOfPages();
  assert.ok(pages > 1, `expected multiple pages, got ${pages}`);
});

jsPDF.API.save = realSave;

console.log(`\n${passed} passed, ${failed} failed`);
process.exit(failed > 0 ? 1 : 0);
